name: hello_world
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  google_fonts: ^2.1.0 
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: DancingScript     
      fonts:
        - asset: fonts/dancing_script.ttf 
  uses-material-design: true 
  assets:
    - images/MyPic.JPG